SELECT 
    CASE GROUPING (YEAR(DATE))
        WHEN 1 THEN 'All Years' ELSE CAST(YEAR(DATE) AS VARCHAR) END AS Year,
    CASE GROUPING (MONTH(DATE))
        WHEN 1 THEN 'All Months' ELSE CAST(MONTH(DATE) AS VARCHAR) END AS Month, 
    CASE GROUPING (HOUR(TIME))
        WHEN 1 THEN 'All Hours' ELSE CAST(HOUR(TIME) AS VARCHAR) END AS Hour, 
    COUNT(*) AS COLLISIONS
FROM COLLISION_ALL
GROUP BY CUBE(YEAR(DATE), MONTH(DATE), HOUR(TIME))
ORDER BY COLLISIONS DESC;


