CREATE TABLE Collision(
    DATE DATE,
    TIME TIME,
    ZIP_CODE VARCHAR(5),
    LATITUDE DOUBLE,
    LONGITUDE DOUBLE,
    CONTRIBUTING_FACTOR_VEHICLE1 VARCHAR(100),
    CONTRIBUTING_FACTOR_VEHICLE2 VARCHAR(100),
    UNIQUE_KEY VARCHAR(24) NOT NULL,
    VEHICLE_TYPE_CODE_1 VARCHAR(100),
    VEHICLE_TYPE_CODE_2 VARCHAR(100),
    PRIMARY KEY (UNIQUE_KEY)
);
