LOAD FROM "C:/Users/Dukyoung/Downloads/NYPD_Motor_Vehicle_Collisions2017.csv" 
OF DEL METHOD P ( 1, 2, 4, 5, 6, 19, 20, 24, 25, 26 ) 
MESSAGES "c:/temp/loadmsg.txt" 
INSERT INTO COLLISION ( DATE, TIME, ZIP_CODE, LATITUDE, LONGITUDE, 
CONTRIBUTING_FACTOR_VEHICLE1, CONTRIBUTING_FACTOR_VEHICLE2, UNIQUE_KEY, 
VEHICLE_TYPE_CODE_1, VEHICLE_TYPE_CODE_2 );