SELECT 
    CASE GROUPING (MONTH(DATE))
        WHEN 1 THEN 'All Months' ELSE CAST(MONTH(DATE) AS VARCHAR) END AS Month, 
    CASE GROUPING (HOUR(TIME))
        WHEN 1 THEN 'All Hours' ELSE CAST(HOUR(TIME) AS VARCHAR) END AS Hour, 
    COUNT(*) AS COLLISIONS
FROM COLLISION
GROUP BY CUBE(MONTH(DATE), HOUR(TIME))
ORDER BY COLLISIONS DESC;

