WITH CR AS (
    SELECT ZIP_CODE, COUNT(*) AS COLLISIONS, RANK() OVER (ORDER BY COUNT(*) DESC) AS COLLISION_RANK 
    FROM COLLISION
    WHERE ZIP_CODE IS NOT NULL
    GROUP BY ZIP_CODE
),
PR AS (
    SELECT ZIP, Population, RANK() OVER (ORDER BY POPULATION DESC) AS POPULATION_RANK
    FROM ZIPCENSUS
    WHERE POPULATION IS NOT NULL
)
SELECT PR.ZIP, CR.COLLISIONS, CR.COLLISION_RANK, PR.Population, PR.POPULATION_RANK
FROM PR
INNER JOIN CR
ON PR.ZIP = CR.ZIP_CODE
WHERE PR.POPULATION_RANK <= 10 AND CR.COLLISION_RANK <= 10;