SELECT ZIP_CODE, LONGITUDE, LATITUDE, COUNT(*) AS COLLISIONS, RANK() OVER (ORDER BY COUNT(*) DESC) AS COLLISION_RANK
FROM COLLISION
WHERE LONGITUDE IS NOT NULL AND LATITUDE IS NOT NULL AND ZIP_CODE IS NOT NULL
GROUP BY ZIP_CODE, LONGITUDE, LATITUDE
FETCH FIRST 10 ROWS ONLY;